POST http://localhost:4001/add-id
Content-Type: application/json

{
  "name": "galigannerao0",
  "email": "n200081@rguktn.ac.in",
  
  "idNumber":"nejdfdssdsdasdsdcdsdadscdassadfdfdddvvbvffsasddsddddsdsddfsaddsfddcassadsadfsdsdssdssddddanfsdgdedfijdfsddfdfdisddsj"
}
