POST https://cheeriobackend-v4ch.onrender.com/add-id
Content-Type: application/json

{
      "name":"Y.Siddhu",
      "idNumber":"N200d00sddsdsdsdsddssasds@081",
       "email":"siddarthyernagula@gmail.com"
    }
 